### ISSUE TITLE
doesn't compile on 32bit Mac OS 10.6.4

### ISSUE THREAD

**Issue by jimsynz** [jeremyevans/home_run#11] opened 2010-09-03 01:36 UTC
I just ran bundler update on my Rails app and was surprised by the following error:

```
Installing home_run (0.9.1) with native extensions /Users/jnh/.rvm/rubies/ruby-1.9.2-p0/lib/ruby/1.9.1/rubygems/installer.rb:483:in `rescue in block in build_extensions': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

/Users/jnh/.rvm/rubies/ruby-1.9.2-p0/bin/ruby extconf.rb 
creating Makefile

make
gcc -I. -I/Users/jnh/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/i386-darwin10.4.0 -I/Users/jnh/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/ruby/backward -I/Users/jnh/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wshorten-64-to-32 -Wno-long-long  -fno-common -pipe -DRUBY19 -Wall   -o date_ext.o -c date_ext.c
date_ext.c: In function 'rhrd__modll':
date_ext.c:114: warning: implicit conversion shortens 64-bit value into a 32-bit value
date_ext.c: In function 'rhrd__unix_to_jd':
date_ext.c:522: warning: implicit conversion shortens 64-bit value into a 32-bit value
date_ext.c: In function 'rhrd_s__ragel_parse':
date_ext.c:1481: warning: unused parameter 'klass'
date_ext.c: In function 'rhrd_s__strptime':
date_ext.c:1494: warning: unused parameter 'klass'
date_ext.c: In function 'rhrd_s_gregorian_leap_q':
date_ext.c:1608: warning: unused parameter 'klass'
date_ext.c: In function 'rhrd_s_julian_leap_q':
date_ext.c:1645: warning: unused parameter 'klass'
date_ext.c: In function 'rhrd_s_today':
date_ext.c:1789: warning: unused parameter 'argv'
date_ext.c: In function 'rhrd_s_valid_civil_q':
date_ext.c:1818: warning: unused parameter 'klass'
date_ext.c: In function 'rhrd_s_valid_commercial_q':
date_ext.c:1858: warning: unused parameter 'klass'
date_ext.c: In function 'rhrd_s_valid_jd_q':
date_ext.c:1893: warning: unused parameter 'argv'
date_ext.c:1893: warning: unused parameter 'klass'
date_ext.c: In function 'rhrd_s_valid_ordinal_q':
date_ext.c:1922: warning: unused parameter 'klass'
date_ext.c: In function 'rhrd_s_zone_to_diff':
date_ext.c:1964: warning: unused parameter 'klass'
date_ext.c: In function 'rhrd_day_fraction':
date_ext.c:2171: warning: unused parameter 'self'
date_ext.c: In function 'rhrd_gregorian_q':
date_ext.c:2251: warning: unused parameter 'self'
date_ext.c: In function 'rhrd_julian_q':
date_ext.c:2316: warning: unused parameter 'self'
date_ext.c: In function 'rhrd_new_start':
date_ext.c:2401: warning: unused parameter 'argv'
date_ext.c: In function 'rhrd_start':
date_ext.c:2422: warning: unused parameter 'self'
gcc -I. -I/Users/jnh/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/i386-darwin10.4.0 -I/Users/jnh/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/ruby/backward -I/Users/jnh/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wshorten-64-to-32 -Wno-long-long  -fno-common -pipe -DRUBY19 -Wall   -o date_parser.o -c date_parser.c
gcc -I. -I/Users/jnh/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/i386-darwin10.4.0 -I/Users/jnh/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1/ruby/backward -I/Users/jnh/.rvm/rubies/ruby-1.9.2-p0/include/ruby-1.9.1 -I. -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE   -fno-common -O3 -ggdb -Wextra -Wno-unused-parameter -Wno-parentheses -Wpointer-arith -Wwrite-strings -Wno-missing-field-initializers -Wshorten-64-to-32 -Wno-long-long  -fno-common -pipe -DRUBY19 -Wall   -o datetime.o -c datetime.c
datetime.c: In function 'rhrdt__nanos_to_hms':
datetime.c:185: warning: implicit conversion shortens 64-bit value into a 32-bit value
datetime.c: In function 'rhrdt__from_jd_nanos':
datetime.c:313: warning: implicit conversion shortens 64-bit value into a 32-bit value
datetime.c:317: warning: implicit conversion shortens 64-bit value into a 32-bit value
datetime.c: In function 'rhrdt__add_days':
datetime.c:360: warning: implicit conversion shortens 64-bit value into a 32-bit value
datetime.c: In function 'rhrdt__fill_from_hash':
datetime.c:435: warning: implicit conversion shortens 64-bit value into a 32-bit value
datetime.c: In function 'rhrdt_s__strptime':
datetime.c:558: warning: unused parameter 'klass'
datetime.c: In function 'rhrdt_s_new_b':
datetime.c:768: warning: implicit conversion shortens 64-bit value into a 32-bit value
datetime.c: In function 'rhrdt_s_now':
datetime.c:789: warning: unused parameter 'argv'
datetime.c: In function 'rhrdt_step':
datetime.c:1454: warning: implicit conversion shortens 64-bit value into a 32-bit value
datetime.c:1473: warning: implicit conversion shortens 64-bit value into a 32-bit value
datetime.c: In function 'rhrdt_to_time':
datetime.c:2597: warning: implicit conversion shortens 64-bit value into a 32-bit value
gcc -dynamic -bundle -o date_ext.bundle date_ext.o date_parser.o datetime.o -L. -L/Users/jnh/.rvm/rubies/ruby-1.9.2-p0/lib -L.  -Wl,-undefined,dynamic_lookup -Wl,-multiply_defined,suppress -Wl,-flat_namespace  -lruby.1.9.1  -lpthread -ldl -lobjc 
ld: duplicate symbol _rhrd_encoding_index in date_parser.o and date_ext.o
collect2: ld returned 1 exit status
make: *** [date_ext.bundle] Error 1
```

**Comment by jeremyevans** [comment] 2010-09-03 02:34
duplicate of #10, already fixed in the master branch.  I'll try to get another gem release out soon, but until then, you can build a gem from the master branch (rake gem).

**Comment by jimsynz** [comment] 2010-09-03 02:39
Oops! Sorry about that. Thanks for the wicket speed boost :)

**Closed as completed** 2010-09-03 09:34 UTC
