### ISSUE TITLE
home_run and ActiveSupport 3.0 dependencies

### ISSUE THREAD

**Issue by pivotalcommon** [jeremyevans/home_run#34] opened 2011-08-10 16:28 UTC
We've gone down the rabbit hole a little more.

_deep breath_

The issue with ActiveSupport and home_run is that ActiveSupport assumes that DateTime object inherits its base from Date object. ActiveSupport modifies Date object plus and minus methods to handle duration objects (1.day, 2.hours, etc).

When looking at date.rb in the base Ruby 1.9.2 implementation, DateTime does inherit from Date.

home_run declares the DateTime object and Date objects as two separate entities.

A lot of these issues could be corrected if home_run's DateTime object inherited correctly from Date. My only _gotchya_ for this would that DateTime should not have certain methods defined for it because it should naturally inherit them from the Date object. Please see date.rb in Ruby 1.9.2 for those methods.

These are the default DateTime methods that are actually defined for DateTime, everything else appears to be inherited from Date object.

``` ruby
require "date"
DateTime.methods - Date.methods
=> [:now] 
DateTime.instance_methods - Date.instance_methods
=> [:hour, :min, :sec, :sec_fraction, :zone, :offset, :new_offset, :minute, :second, :second_fraction]
DateTime.private_methods - Date.private_methods
=> [:today]
```

etc....

**Comment by jeremyevans** [comment] 2011-08-10 16:44
This behavior is not a bug, it's by design.  Note that ruby 1.9.3's date/datetime implementation (switch_hitter) has the same issue.  This is an ActiveSupport bug, which they fixed in trunk but didn't backport to 3.0-stable.  This is the patch that they need to backport:

https://github.com/rails/rails/commit/33f222b9e1b20aa6264084ec2c8c3206e1c2d598#activesupport/lib/active_support/core_ext/date_time/calculations.rb

You could ask ActiveSupport maintainers to backport that commit to 3.0-stable, since it's their bug.  They shouldn't be depending on DateTime inheriting methods from Date versus DateTime implementing the methods itself.  That's an internal implementation detail.

I actually added a bug for this to Rails lighthouse late last year (before they switched to GitHub Issues): https://rails.lighthouseapp.com/projects/8994-ruby-on-rails/tickets/6062 . I guess I just didn't get enough +1s.

**Closed as completed by jeremyevans** 2011-08-10 16:44 UTC
